Wdp220602 1
kamilwilk95/wdp-2206-02 pull request #12
Opened 2022-06-11 14:15 UTC by sicArchitect

I added a property image to ProductBox.propTypes.  
`ProductBox.propTypes = {
  children: PropTypes.node,
  name: PropTypes.string,
  price: PropTypes.number,
  image: PropTypes.string,
  promo: PropTypes.string,
  stars: PropTypes.number,
};`
I added only one photo to set the design on the card. If it's necessary I can add an array of photos.

2022-06-12 08:49 UTC, kamilwilk95 requested changes

2022-06-12 08:49 UTC, kamilwilk95 commented on src/App.js
> +  <BrowserRouter>
po co ta zamiana miejsc?

2022-06-12 08:49 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.module.scss
> +      size: cover;
Nie ma takiej właściwości

2022-06-12 08:49 UTC, kamilwilk95 commented on src/redux/initialState.js
> +      image: './images/fornitures-bed.jpg',
Dlaczego tylko jeden produkt ma zdjęcie?

2022-06-12 19:39 UTC, kamilwilk95 approved these changes

2022-06-12 20:13 UTC, sicArchitect commented
Dodałem zdjęcia
`left: 0;
      height: 100%;
      width: 100%;
      size: cover;`
      
Gdy usunąłem te właściwości zdjęcie zmienia pozycje.
https://github.com/kamilwilk95/wdp-2206-02/pull/12/commits/ac026fc8b8459ac7ab0f48d6f11938461769a128

2022-06-13 11:39 UTC, sicArchitect commented
Gdzie pojawiły się konflikty i jak je mogę znaleźć?

2022-06-13 16:48 UTC, sicArchitect commented
Poprawiłem konflikty.

2022-06-13 16:49 UTC, sicArchitect commented
Poprawiłem konflikty

2022-06-14 21:55 UTC, sicArchitect commented
To w jaki sposób mogę nanieść swoje zmiany skoro pojawia mi się przez to konflikt

2022-06-15 06:39 UTC, merged