Wdp220602 22
kamilwilk95/wdp-2206-02 pull request #27
Opened 2022-06-19 21:36 UTC by sbjohansen

Komponent stworzony. Funkcjonalność jeśli chodzi o pobieranie nazwy itd stworzę przy tasku 23, gdzie będe się skupiać na działaniu komponentu, tutaj wydawało mi się to zbędne. Dodałem placeholdery name/price etc.

2022-06-20 07:08 UTC, sicArchitect reviewed
Wszystko jest zgodne z instrukcją

2022-06-20 07:08 UTC, sicArchitect commented on src/components/features/PromotedBox/PromotedBox.js
> +  //console.log('test')
Czy będziesz potrzebował jeszcze `console.log()`

2022-06-20 16:12 UTC, sbjohansen commented
Dziwne, u mnie lokalnie było. Sprawdze po pracy w nocy

2022-06-20 16:18 UTC, sbjohansen commented
Dziwne, u mnie lokalnie było. Sprawdze po pracy w nocy.

Było dodane w tym commit https://github.com/kamilwilk95/wdp-2206-02/commit/0d70e75ebbaf35659214ac7884d27ea466f465dd

2022-06-20 16:58 UTC, Jacob120 commented
> > 
> 
> Na pewno? A gdzie są "Wyróżnione produkty po prawej". Odpaliłem projekt u siebie u tego nie ma

U mnie się wyświetlają też elementy wszystkie po prawej stronie.

2022-06-20 17:00 UTC, Jacob120 commented on src/components/features/PromotedBox/PromotedBox.module.scss
> +  opacity: 0.9;
ja bym zmniejszył opacity na 0.6 / 0.7 i zrobił to tak, żeby biały tekst, który jest w tym elemencie miał opacity: 1; Będzie lepiej widać zdjęcie, które jest pod spodem i będzie to wtedy wyglądało jak w designie

2022-06-20 17:07 UTC, Jacob120 requested changes

2022-06-20 21:32 UTC, sbjohansen commented on src/components/features/PromotedBox/PromotedBox.module.scss
> +  opacity: 0.9;
Zgadzam się. Zmienione na 0.7,a text opacity na 1.

2022-06-20 21:34 UTC, sbjohansen commented
> > 
> 
> Na pewno? A gdzie są "Wyróżnione produkty po prawej". Odpaliłem projekt u siebie u tego nie ma

Sprawdziłem u siebie, wygląda to tak:

![image](https://user-images.githubusercontent.com/93682845/174680339-84eb75f8-5824-461f-bec6-0e42d0573637.png)

Również na remote branchu, więc wygląda na to, że github się zbugował i zatrzymał się na wcześniejszym commit'cie który rzeczywiście nie zawierał prawej strony jeszcze.

2022-06-21 05:43 UTC, kamilwilk95 approved these changes

2022-06-21 07:28 UTC, Jacob120 approved these changes

2022-06-21 07:32 UTC, sicArchitect approved these changes

2022-06-21 11:43 UTC, merged