Wdp220602 5 Add compare state in initialState -> products
kamilwilk95/wdp-2206-02 pull request #9
Opened 2022-06-10 17:25 UTC by Jacob120

2022-06-10 20:00 UTC, kamilwilk95 requested changes

2022-06-10 20:25 UTC, Jacob120 commented on src/components/common/ProductBox/ProductBox.js
> +  compare: PropTypes.bool,
Będę wdzięczny za rozwinięcie. W tasku mamy "Brak ostylowanych stanów "ulubiony" oraz "dodany do porównania". Jak rozumiem chodzi o odpowiednie ostylowanie przycików favorite i add to compare oraz odpowiednia zmiana stanu

2022-06-12 08:44 UTC, kamilwilk95 commented on src/components/common/ProductBox/ProductBox.js
> +  compare: PropTypes.bool,
Nie, chodzi o propTypes, tutaj dodałeś 3 nowe pola, w propTypes newFurniture też jest opis produktu i tam nie dodałeś

2022-06-12 10:44 UTC, Jacob120 commented on src/components/common/ProductBox/ProductBox.js
> +  compare: PropTypes.bool,
Poprawione :).

2022-06-12 19:50 UTC, kamilwilk95 approved these changes

2022-06-12 19:50 UTC, merged